### ISSUE TITLE
Python issues with installing Seurat

### ISSUE THREAD

**Issue by lgeistlinger** [Bioconductor/ISMB.OSCA#10]
I am having some trouble installing [Seurat](https://cran.r-project.org/web/packages/Seurat/index.html) - which has an extensive dependency list. It also includes dependencies that depend on `python` causing the [GHA to fail](https://github.com/Bioconductor/ISMB.OSCA/actions/runs/5313892228/jobs/9620403854) at the `Install system dependencies` step:

```
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  2to3 python2-minimal python2 dh-python python-is-python3

E: Package 'python' has no installation candidate
Error: Process completed with exit code 100.
```

What I have tried so far to resolve this:

1. including an `apt-get -y install python3.8-venv` command in the GHA for installing python [e064246](https://github.com/Bioconductor/ISMB.OSCA/commit/e0642467a5eee06b89b9a7dcf802b369284ca299)
2.  including an `apt-get -y install python-is-python3` command in the GHA [b4b8708](https://github.com/Bioconductor/ISMB.OSCA/commit/b4b87085f91a25582f6ca0e06909df2c0243db0e)
3. And following a [related discussion](https://community-bioc.slack.com/archives/CJDMYKG2U/p1686832117562189) in the #biocworkshops channel on Bioc slack, I tried using the `setup-python` chunk in the GHA [06a625c](https://github.com/Bioconductor/ISMB.OSCA/commit/06a625cf792dbfcd0bb9d3ad63d64e26895337e3) 

Without success so far.
I have factored out the problem to a minimal github repo that mimics most of the behavior here, but only has Seurat in `Imports` to further troubleshoot this:

https://github.com/lgeistlinger/gha-python-test

Interestingly no such problems occur with importing `zellkonverter` which also depends on reticulate and python [5a1f8d1](https://github.com/Bioconductor/ISMB.OSCA/commit/5a1f8d15ea0a4dd74a2ab75e54eda609de9462dd).

**Comment by lgeistlinger** [comment]
Not sure whether you have any ideas on how to best resolve this, maybe @LiNk-NY @almahmoud @seandavi ?

**Comment by vjcitn** [comment]
A related event has been discussed here: https://community-bioc.slack.com/archives/CJDMYKG2U/p1686813772433829

**Comment by lgeistlinger** [comment]
The solution in the slack thread indeed also does the trick here. Thanks Vince!

**Comment by mtmorgan** [comment]
In my own work I found that I did NOT have to comment out the lines at https://github.com/Bioconductor/ISMB.OSCA/blob/fced40e316fb68f5fe14d17c3074a70daf50cda8/.github/workflows/basic_checks.yaml#L67-L72.

I encountered this when running a clone of https://github.com/Bioconductor/BuildABiocWorkshop which is where I guess this repository also originates. Should this be fixed upstream somewhere?? Maybe the step could be deleted (since bioconductor_docker already has most system dependencies?) or is the right solution to make this more sophisticated, maybe talking with whoever maintains the sysreq package? @almahmoud

**Comment by LiNk-NY** [comment]
Thanks Martin!

That was also my inclination but there may be some workshops that use external system dependencies. An analysis of repositories inheriting from the template would be good to see.

I wonder if removing the r-setup and deps installation steps would also work:
https://github.com/Bioconductor/ISMB.OSCA/blob/fced40e316fb68f5fe14d17c3074a70daf50cda8/.github/workflows/basic_checks.yaml#L34-L40

Does the python / reticulate installation require R to be in a certain location?
I can try to test this in a PR.
