### ISSUE TITLE
possibly missing BiocPkgTools dependency

### ISSUE THREAD

**Issue by billila** [Bioconductor/ISMB.OSCA#16]
possibly missing BiocPkgTools dependency in: 
https://github.com/Bioconductor/ISMB.OSCA/blob/46cd58afb66b681bb1f75d6adc7a3dc6f0fd00a6/vignettes/large_data.Rmd#L442
https://github.com/Bioconductor/ISMB.OSCA/blob/46cd58afb66b681bb1f75d6adc7a3dc6f0fd00a6/vignettes/large_data.Rmd#L452

**Comment by lgeistlinger** [comment]
Thanks @billila - this functionality comes from the `BiocStyle` package (which we have in `Suggests`)
