### ISSUE TITLE
error in hca.Rmd

### ISSUE THREAD

**Issue by lgeistlinger** [Bioconductor/ISMB.OSCA#18]
Hi @LiNk-NY - there seems to be an issue with one of the exercises in the `hca.Rmd` vignette, can you have a look:

https://github.com/Bioconductor/ISMB.OSCA/actions/runs/5468326108/jobs/9955807593

```
Quitting from lines 333-343 [unnamed-chunk-23] (hca.Rmd)
Error: processing vignette 'hca.Rmd' failed with diagnostics:
In index: 1.
With name: counts.
Caused by error in `dplyr::summarise()`:
In argument: `sces = list(...)`.
Caused by error:
! assert_that: length of assertion is not 1
```

**Comment by LiNk-NY** [comment]
It looks like the macrophages are not in the query anymore. I have changed it to `cd8 tem` cells .

**Comment by LiNk-NY** [comment]
https://github.com/Bioconductor/ISMB.OSCA/commit/e26a07983ee1eef7b6e4c413c98c1a8cb39580b8

**Comment by lgeistlinger** [comment]
Thanks. Looking good.
